### PR TITLE
fix(template): Add Area listing to title and body

### PR DESCRIPTION
**Pull request by mindreeper2420**
Closes https://github.com/openshiftio/openshift.io/issues/644

### CODE REVIEW

**Comment by joshuawilson** [comment]
These appear to be fixed not dynamic. It should read the `area` and add it. The point is that not all work items are planner issues.

**Comment by mindreeper2420** [comment]
I spoke with Aslak before filing this PR and he will be hooking in the dynamic code. This was to place and style how the Area info should appear.

**Comment by joshuawilson** [comment]
ah, ok

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-44-1`

**Comment by aslakknutsen** [comment]
[test]

**Pull request merged**
