### PR TITLE
fix(templates): update the templates with new design

### PR DESCRIPTION
**Pull request by mindreeper2420**
update the templates to include the new designs from UX

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@aslakknutsen two of these templates (the `workitem.update` and `comment.update`) just have placeholders right now, due to the need for the historical information.

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-4`

**Comment by aslakknutsen** [comment]
@mindreeper2420 Pushed a few template fixes to your branch.

Comments:

* Spacename border is missing the right side in chrome?
* 'performed by user' no longer link to user profile?
* Whats the link on Type in WorkItem.Create suppose to be?
* Should "spacename" be "account/spacename" ?

Current v rendered versions:
screenshot from 2017-08-16 01-11-39
screenshot from 2017-08-16 01-11-17
screenshot from 2017-08-16 01-11-28
screenshot from 2017-08-16 01-11-05

**Comment by mindreeper2420** [comment]
@aslakknutsen thanks for looking them over and pushing fixes. I went through and updated the templates to address some of the issues you found:
* Spacename border is missing the right side in chrome?
  - I ran this through Chrome and all of the borders are appearing for me. Not sure why that is happening when the templates are filled in. 
* 'performed by user' no longer link to user profile?
  - This was an error with copy/paste. I've changed it back to link to the user's profile
* Whats the link on Type in WorkItem.Create suppose to be?
  - There should not be a link. I've removed it.
* Should "spacename" be "account/spacename" ?
  - Yes, that would make a lot more sense in the overall scheme of the product. Can you change that?

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-5`

**Comment by aslakknutsen** [comment]
@mindreeper2420 Heres the HTML output if you want to debug the css right border issue; https://gist.github.com/aslakknutsen/33e6280c693216f65c534e3e73a6c431

**Comment by aslakknutsen** [comment]
> Should "spacename" be "account/spacename" ?

Fixed

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-6`

**Comment by aslakknutsen** [comment]
A few more examples with some different data. Some of them 'might' need some tweaks ;)

screenshot from 2017-08-16 02-57-50
screenshot from 2017-08-16 03-00-34
screenshot from 2017-08-16 02-57-02

**Comment by mindreeper2420** [comment]
@aslakknutsen yikes...those are...interesting

* The first example, while out of place, at least fits in the template, so I'm ok with that. It is difficult to  determine how someone will add text in there, being that it supports markdown (though why the "description" title is added in a box labelled "description" in Planner is odd to me, but ¯\_(ツ)_/¯)

* For the second one, that should have been constrained by the width of the notification, but I'll add a max-width field to it to be certain.

* The third one is odd. If that is all text entered into the markdown field, shouldn't it wrap in the template? The max-width constraint may help with this, but it does seem odd to me.

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-7`

**Comment by aslakknutsen** [comment]
> The first example, while out of place, at least fits in the template, so I'm ok with that. It is difficult to determine how someone will add text in there, being that it supports markdown (though why the "description" title is added in a box labelled "description" in Planner is odd to me, but ¯_(ツ)_/¯)

Yeah, it's a Planner odd thing. But what about the "Description" label on the side, align top?

Or even:

    Description:
    real description starts here
    and continues here

As oppose to today

    Description:      real description starts here
                      and continues here

I know the current follows the Details view in Planner, but I personally find that to be wrong as well :)

**Comment by aslakknutsen** [comment]
> The third one is odd. If that is all text entered into the markdown field, shouldn't it wrap in the template? The max-width constraint may help with this, but it does seem odd to me.

It comes out as a <pre> so maybe a pre-wrap would do here?

**Comment by aslakknutsen** [comment]
@mindreeper2420 I made you a little preview tool. If you rebase this branch on top of master you can do "make preview" and it will render the templates shown above: https://github.com/fabric8-services/fabric8-notification/pull/37

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-8`

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-9`

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-10`

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-12`

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-13`

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-14`

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-notification image is available for testing.  `docker pull docker.io/fabric8/fabric8-notification:SNAPSHOT-PR-36-15`

**Pull request merged**
